version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache-software
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - ./src:/var/www/html/
    ports:
      - '9090:80'
  database:
    container_name: database
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0123
      MYSQL_DATABASE: DatabaseProject
      MYSQL_USER: Master
      MYSQL_PASSWORD: 0123
    ports:
      - '8906:3306'
    volumes:
      - ./my-datavolume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - '9000:80'
    restart: always
    environment:
      PMA_HOST: database
    depends_on:
      - database